### ISSUE TITLE
When i try running for chrome it says : Error: Cannot find module 'win-dpapi'

### ISSUE THREAD

**Issue by obiwan245** [Kalininator/cookie-thief#16]
Posting full code with full error below (Worked perfectly for firefox but not for chrome)

index.js
----------------------------------------------------
const { getCookie, listCookies, Browser } = require('cookie-thief')
async function chromeit() {
    const cookies = await listCookies({
        browser: Browser.Firefox,
      });
      console.log(cookies);
}
chromeit()
--------------------------------------------------

node index.js
--------------------------------------------------
(node:2016) UnhandledPromiseRejectionWarning: Error: Cannot find module 'win-dpapi'
Require stack:
- C:\Users\obi\Documents\CookiesMonster\node_modules\cookie-thief\lib\chrome\optionalDependencies.js
- C:\Users\obi\Documents\CookiesMonster\node_modules\cookie-thief\lib\chrome\decrypt.js
- C:\Users\obi\Documents\CookiesMonster\node_modules\cookie-thief\lib\chrome\index.js
- C:\Users\obi\Documents\CookiesMonster\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at getDpapi (C:\Users\obi\Documents\CookiesMonster\node_modules\cookie-thief\lib\chrome\optionalDependencies.js:18:13)
    at decryptWindows (C:\Users\obi\Documents\CookiesMonster\node_modules\cookie-thief\lib\chrome\decrypt.js:27:55)
    at C:\Users\obi\Documents\CookiesMonster\node_modules\cookie-thief\lib\chrome\index.js:82:60
    at Generator.next (<anonymous>)
    at C:\Users\obi\Documents\CookiesMonster\node_modules\cookie-thief\lib\chrome\index.js:8:71
    at new Promise (<anonymous>)

**Comment by Kalininator** [comment]
The reason i ask is the error is showing that `win-dpapi` was not installed. it probably didnt error because its an optional dependency. its optional because its only there for when its installed on windows.  
So for some reason `win-dpapi` didn't install. 
Would be helpful if you had the log of the install output for either this package, or maybe can try just install `win-dpapi` and see if that succeeds

**Comment by obiwan245** [comment]
i tried just now. same problem

**Comment by Kalininator** [comment]
@obiwan245 Hey, can't seem to recreate the issue. have you tried the steps in here? looks like its same issue https://stackoverflow.com/a/45840283

Currently got a WIP change to make sure the appropriate platform modules are installed, so this problem should get flagged up during package installation. Will look to add some notes in the docs about this issue on windows as well, hopefully this weeked
